{"elemID":"component_732","date":"6/5/2020","time":"12:00am","name":"summary","pathname":"summary","pathstr":"async.until~summary","path":[["/","async"],[".","until"],["~","summary"]],"flags":[],"source":[["/","async"],[".","until"]],"sourcestr":"async.until","superClasses":[],"interfaces":[],"satisfies":[],"ctype":"spare","valtype":[],"isKwarg":false,"isMultiArg":false,"isSpare":true,"isModule":false,"isClass":false,"simpleCtype":"spare","hideCtype":false,"spares":[],"modules":[],"enums":[],"statics":[],"functions":[],"members":[],"methods":[],"localValues":[],"localFunctions":[],"arguments":[],"finalArgs":[],"finalKwargs":[],"returns":[],"throws":[],"names":[],"events":[],"signatures":[],"propertySymbols":[],"memberSymbols":[],"returnsSymbols":[],"hasChildren":true,"isTotallyEmpty":false,"doc":[{"doc":"\n\nRepeatedly call `fn` until `test` returns `true`. Calls `callback` when\nstopped, or an error occurs. `callback` will be passed an error and any\narguments passed to the final `fn`'s callback.\n\nThe inverse of [whilst]{@link module:ControlFlow.whilst}.\n\nexecution of `fn`. Invoked with ().\nThe function is passed a `callback(err)`, which must be called once it has\ncompleted with an optional `err` argument. Invoked with (callback).\nfunction has passed and repeated execution of `fn` has stopped. `callback`\nwill be passed an error and any arguments passed to the final `fn`'s\ncallback. Invoked with (err, [results]);\n\n","context":[]}],"breadcrumbs":[{"path":[["/","async"]],"name":"async","delimiter":"/"},{"path":[["/","async"],[".","until"]],"name":"until","delimiter":"."},{"path":[["/","async"],[".","until"],["~","summary"]],"name":"summary","delimiter":"~"}],"sanitaryName":"summary_1","baseTagPath":"../../../../../../"}
