{"elemID":"component_743","date":"6/5/2020","time":"12:00am","name":"summary","pathname":"summary","pathstr":"async.whilst~summary","path":[["/","async"],[".","whilst"],["~","summary"]],"flags":[],"source":[["/","async"],[".","whilst"]],"sourcestr":"async.whilst","superClasses":[],"interfaces":[],"satisfies":[],"ctype":"spare","valtype":[],"isKwarg":false,"isMultiArg":false,"isSpare":true,"isModule":false,"isClass":false,"simpleCtype":"spare","hideCtype":false,"spares":[],"modules":[],"enums":[],"statics":[],"functions":[],"members":[],"methods":[],"localValues":[],"localFunctions":[],"arguments":[],"finalArgs":[],"finalKwargs":[],"returns":[],"throws":[],"names":[],"events":[],"signatures":[],"propertySymbols":[],"memberSymbols":[],"returnsSymbols":[],"hasChildren":true,"isTotallyEmpty":false,"doc":[{"doc":"\n\nRepeatedly call `fn`, while `test` returns `true`. Calls `callback` when\nstopped, or an error occurs.\n\nexecution of `fn`. Invoked with ().\nThe function is passed a `callback(err)`, which must be called once it has\ncompleted with an optional `err` argument. Invoked with (callback).\nfunction has failed and repeated execution of `fn` has stopped. `callback`\nwill be passed an error and any arguments passed to the final `fn`'s\ncallback. Invoked with (err, [results]);\n\n### Example\n```javascript\n\nvar count = 0;\nasync.whilst(\n    function() { return count < 5; },\n    function(callback) {\n        count++;\n        setTimeout(function() {\n            callback(null, count);\n        }, 1000);\n    },\n    function (err, n) {\n        // 5 seconds have passed, n = 5\n    }\n);\n\n```\n\n","context":[]}],"breadcrumbs":[{"path":[["/","async"]],"name":"async","delimiter":"/"},{"path":[["/","async"],[".","whilst"]],"name":"whilst","delimiter":"."},{"path":[["/","async"],[".","whilst"],["~","summary"]],"name":"summary","delimiter":"~"}],"sanitaryName":"summary_1","baseTagPath":"../../../../../../"}
