{"elemID":"component_299","date":"6/5/2020","time":"12:00am","name":"details","pathname":"details","pathstr":"async.each~details","path":[["/","async"],[".","each"],["~","details"]],"flags":[],"source":[["/","async"],[".","each"]],"sourcestr":"async.each","superClasses":[],"interfaces":[],"satisfies":[],"ctype":"spare","valtype":[],"isKwarg":false,"isMultiArg":false,"isFunction":false,"isSpare":true,"isModule":false,"isClass":false,"simpleCtype":"spare","hideCtype":false,"spares":[],"modules":[],"enums":[],"statics":[],"functions":[],"members":[],"methods":[],"localValues":[],"localFunctions":[],"arguments":[],"finalArgs":[],"finalKwargs":[],"returns":[],"throws":[],"names":[],"events":[],"signatures":[],"propertySymbols":[],"memberSymbols":[],"returnsSymbols":[],"hasChildren":false,"doc":[{"doc":"\n*\n     * Applies the function `iteratee` to each item in `coll`, in parallel.\n     * The `iteratee` is called with an item from the list, and a callback for when\n     * it has finished. If the `iteratee` passes an error to its `callback`, the\n     * main `callback` (for the `each` function) is immediately called with the\n     * error.\n     *\n     * Note, that since this function applies `iteratee` to each item in parallel,\n     * there is no guarantee that the iteratee functions will complete in order.\n     *\n     * @name each\n     * @static\n     * @memberOf module:Collections\n     * @method\n     * @alias forEach\n     * @category Collection\n     * @param {Array|Iterable|Object} coll - A collection to iterate over.\n     * @param {Function} iteratee - A function to apply to each item\n     * in `coll`. The iteratee is passed a `callback(err)` which must be called once\n     * it has completed. If no error has occurred, the `callback` should be run\n     * without arguments or with an explicit `null` argument. The array index is not\n     * passed to the iteratee. Invoked with (item, callback). If you need the index,\n     * use `eachOf`.\n     * @param {Function} [callback] - A callback which is called when all\n     * `iteratee` functions have finished, or an error occurs. Invoked with (err).\n     * @example\n     *\n     * // assuming openFiles is an array of file names and saveFile is a function\n     * // to save the modified contents of that file:\n     *\n     * async.each(openFiles, saveFile, function(err){\n     *   // if any of the saves produced an error, err would equal that error\n     * });\n     *\n     * // assuming openFiles is an array of file names\n     * async.each(openFiles, function(file, callback) {\n     *\n     *     // Perform operation on file here.\n     *     console.log('Processing file ' + file);\n     *\n     *     if( file.length > 32 ) {\n     *       console.log('This file name is too long');\n     *       callback('File name too long');\n     *     } else {\n     *       // Do work to process file here\n     *       console.log('File processed');\n     *       callback();\n     *     }\n     * }, function(err) {\n     *     // if any of the file processing produced an error, err would equal that error\n     *     if( err ) {\n     *       // One of the iterations produced an error.\n     *       // All processing will now stop.\n     *       console.log('A file failed to process');\n     *     } else {\n     *       console.log('All files have been processed successfully');\n     *     }\n     * });\n","context":[]}],"breadcrumbs":[{"path":[["/","async"]],"name":"async","delimiter":"/"},{"path":[["/","async"],[".","each"]],"name":"each","delimiter":"."},{"path":[["/","async"],[".","each"],["~","details"]],"name":"details","delimiter":"~"}],"baseTagPath":"../../../../../../"}