{"elemID":"component_349","date":"6/5/2020","time":"12:00am","name":"summary","pathname":"summary","pathstr":"async.each~summary","path":[["/","async"],[".","each"],["~","summary"]],"flags":[],"source":[["/","async"],[".","each"]],"sourcestr":"async.each","superClasses":[],"interfaces":[],"satisfies":[],"ctype":"spare","valtype":[],"isKwarg":false,"isMultiArg":false,"isSpare":true,"isModule":false,"isClass":false,"simpleCtype":"spare","hideCtype":false,"spares":[],"modules":[],"enums":[],"statics":[],"functions":[],"members":[],"methods":[],"localValues":[],"localFunctions":[],"arguments":[],"finalArgs":[],"finalKwargs":[],"returns":[],"throws":[],"names":[],"events":[],"signatures":[],"propertySymbols":[],"memberSymbols":[],"returnsSymbols":[],"hasChildren":true,"isTotallyEmpty":false,"doc":[{"doc":"\n\nApplies the function `iteratee` to each item in `coll`, in parallel.\nThe `iteratee` is called with an item from the list, and a callback for when\nit has finished. If the `iteratee` passes an error to its `callback`, the\nmain `callback` (for the `each` function) is immediately called with the\nerror.\n\nNote, that since this function applies `iteratee` to each item in parallel,\nthere is no guarantee that the iteratee functions will complete in order.\n\nin `coll`. The iteratee is passed a `callback(err)` which must be called once\nit has completed. If no error has occurred, the `callback` should be run\nwithout arguments or with an explicit `null` argument. The array index is not\npassed to the iteratee. Invoked with (item, callback). If you need the index,\nuse `eachOf`.\n`iteratee` functions have finished, or an error occurs. Invoked with (err).\n\n### Example\n```javascript\n\n// assuming openFiles is an array of file names and saveFile is a function\n// to save the modified contents of that file:\n\nasync.each(openFiles, saveFile, function(err){\n  // if any of the saves produced an error, err would equal that error\n});\n\n// assuming openFiles is an array of file names\nasync.each(openFiles, function(file, callback) {\n\n    // Perform operation on file here.\n    console.log('Processing file ' + file);\n\n    if( file.length > 32 ) {\n      console.log('This file name is too long');\n      callback('File name too long');\n    } else {\n      // Do work to process file here\n      console.log('File processed');\n      callback();\n    }\n}, function(err) {\n    // if any of the file processing produced an error, err would equal that error\n    if( err ) {\n      // One of the iterations produced an error.\n      // All processing will now stop.\n      console.log('A file failed to process');\n    } else {\n      console.log('All files have been processed successfully');\n    }\n});\n\n```\n\n","context":[]}],"breadcrumbs":[{"path":[["/","async"]],"name":"async","delimiter":"/"},{"path":[["/","async"],[".","each"]],"name":"each","delimiter":"."},{"path":[["/","async"],[".","each"],["~","summary"]],"name":"summary","delimiter":"~"}],"sanitaryName":"summary","baseTagPath":"../../../../../../"}
